-- Creates the medical_codes reference table and seeds it with the
-- curated ICD-10 / SNOMED CT lists. From now on this table (not the
-- static JS files) is the live source for search/stats/admin-add.
CREATE TABLE IF NOT EXISTS medical_codes (
  id SERIAL PRIMARY KEY,
  system VARCHAR(10) NOT NULL CHECK (system IN ('icd','snomed')),
  code VARCHAR(20) NOT NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  icd_link VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(system, code)
);
CREATE INDEX IF NOT EXISTS idx_medical_codes_system ON medical_codes(system);
CREATE INDEX IF NOT EXISTS idx_medical_codes_search ON medical_codes USING GIN (to_tsvector('simple', name_ar || ' ' || name_en || ' ' || code));

INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A09', 'التهاب معوي وقولون معدي المنشأ', 'Gastroenteritis and colitis of infectious origin') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A15', 'السل الرئوي', 'Respiratory tuberculosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B15', 'التهاب الكبد A الحاد', 'Acute hepatitis A') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B16', 'التهاب الكبد B الحاد', 'Acute hepatitis B') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B18', 'التهاب الكبد الفيروسي المزمن', 'Chronic viral hepatitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B20', 'مرض فيروس نقص المناعة البشرية (HIV)', 'HIV disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B34', 'عدوى فيروسية غير محددة', 'Viral infection, unspecified') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'C50', 'ورم خبيث بالثدي', 'Malignant neoplasm of breast') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'C61', 'ورم خبيث بالبروستاتا', 'Malignant neoplasm of prostate') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'C34', 'ورم خبيث بالشعبتين والرئة', 'Malignant neoplasm of bronchus and lung') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'D50', 'فقر دم بعوز الحديد', 'Iron deficiency anemia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'D64', 'فقر دم آخر', 'Other anemias') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E03', 'قصور الغدة الدرقية', 'Hypothyroidism') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E05', 'فرط نشاط الغدة الدرقية', 'Thyrotoxicosis (Hyperthyroidism)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E10', 'داء السكري النوع الأول', 'Type 1 diabetes mellitus') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E11', 'داء السكري النوع الثاني', 'Type 2 diabetes mellitus') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E66', 'السمنة', 'Obesity') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E78', 'اضطراب استقلاب الدهون (الكوليسترول)', 'Disorders of lipoprotein metabolism') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E86', 'نقص الحجم (الجفاف)', 'Volume depletion (Dehydration)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F32', 'نوبة اكتئابية', 'Depressive episode') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F41', 'اضطرابات القلق الأخرى', 'Other anxiety disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F51', 'اضطرابات النوم غير العضوية', 'Nonorganic sleep disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G40', 'الصرع', 'Epilepsy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G43', 'الصداع النصفي', 'Migraine') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G47', 'اضطرابات النوم', 'Sleep disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H10', 'التهاب الملتحمة', 'Conjunctivitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H25', 'الساد الشيخوخي (المياه البيضاء)', 'Senile cataract') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H52', 'اضطرابات انكسار الضوء وتكيف العين', 'Disorders of refraction and accommodation') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H60', 'التهاب الأذن الخارجية', 'Otitis externa') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H66', 'التهاب الأذن الوسطى القيحي', 'Suppurative otitis media') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I10', 'ارتفاع ضغط الدم الأساسي', 'Essential (primary) hypertension') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I20', 'الذبحة الصدرية', 'Angina pectoris') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I21', 'احتشاء عضلة القلب الحاد', 'Acute myocardial infarction') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I48', 'الرجفان الأذيني والرفرفة', 'Atrial fibrillation and flutter') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I50', 'قصور القلب', 'Heart failure') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I63', 'احتشاء دماغي (سكتة دماغية)', 'Cerebral infarction (Stroke)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I83', 'دوالي الأطراف السفلية', 'Varicose veins of lower extremities') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J00', 'الزكام الحاد (نزلة برد)', 'Acute nasopharyngitis (Common cold)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J01', 'التهاب الجيوب الأنفية الحاد', 'Acute sinusitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J02', 'التهاب البلعوم الحاد', 'Acute pharyngitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J03', 'التهاب اللوزتين الحاد', 'Acute tonsillitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J06', 'عدوى الجهاز التنفسي العلوي الحادة', 'Acute upper respiratory infection') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J18', 'الالتهاب الرئوي', 'Pneumonia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J20', 'التهاب الشعب الهوائية الحاد', 'Acute bronchitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J44', 'مرض الانسداد الرئوي المزمن (COPD)', 'Chronic obstructive pulmonary disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J45', 'الربو', 'Asthma') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K02', 'تسوس الأسنان', 'Dental caries') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K21', 'ارتجاع المريء (GERD)', 'Gastro-esophageal reflux disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K25', 'قرحة المعدة', 'Gastric ulcer') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K29', 'التهاب المعدة والاثني عشر', 'Gastritis and duodenitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K35', 'التهاب الزائدة الدودية الحاد', 'Acute appendicitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K58', 'متلازمة القولون العصبي', 'Irritable bowel syndrome') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K59', 'اضطرابات وظيفية أخرى بالأمعاء (إمساك)', 'Other functional intestinal disorders (Constipation)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K80', 'حصى المرارة', 'Cholelithiasis (Gallstones)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L20', 'الأكزيما التأتبية', 'Atopic dermatitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L23', 'التهاب الجلد التماسي التحسسي', 'Allergic contact dermatitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L30', 'التهاب الجلد الآخر', 'Other dermatitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L40', 'الصدفية', 'Psoriasis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L50', 'الشرى (الأرتيكاريا)', 'Urticaria') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M15', 'الفصال العظمي المتعدد المفاصل', 'Polyosteoarthritis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M19', 'الفصال العظمي الآخر', 'Other osteoarthritis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M25', 'اضطرابات مفصلية أخرى', 'Other joint disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M54', 'ألم الظهر', 'Dorsalgia (Back pain)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M06', 'التهاب المفاصل الروماتويدي', 'Rheumatoid arthritis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M10', 'النقرس', 'Gout') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M79', 'اضطرابات نسيج رخو أخرى', 'Other soft tissue disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N10', 'التهاب الكلية والحويضة الحاد', 'Acute pyelonephritis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N18', 'مرض الكلى المزمن', 'Chronic kidney disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N20', 'حصى الكلى والحالب', 'Calculus of kidney and ureter') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N30', 'التهاب المثانة', 'Cystitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N39', 'اضطرابات الجهاز البولي الأخرى (عدوى مسالك بولية)', 'Other urinary system disorders (UTI)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N40', 'تضخم البروستاتا الحميد', 'Benign prostatic hyperplasia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O26', 'رعاية الأم لحالات أخرى بالحمل', 'Maternal care for other conditions related to pregnancy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O80', 'ولادة طبيعية وحيدة', 'Single spontaneous delivery') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z34', 'مراقبة حمل طبيعي', 'Supervision of normal pregnancy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S06', 'إصابة داخل القحف', 'Intracranial injury') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S52', 'كسر الساعد', 'Fracture of forearm') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S82', 'كسر أسفل الساق بما فيها الكاحل', 'Fracture of lower leg, including ankle') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'T14', 'إصابة بمنطقة جسدية غير محددة', 'Injury of unspecified body region') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R05', 'السعال', 'Cough') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R07', 'ألم بالحلق والصدر', 'Pain in throat and chest') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R10', 'ألم بالبطن والحوض', 'Abdominal and pelvic pain') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R11', 'غثيان وقيء', 'Nausea and vomiting') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R50', 'حمى غير معروفة السبب', 'Fever of unknown origin') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R51', 'الصداع', 'Headache') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R53', 'الشعور بالتوعك والإرهاق', 'Malaise and fatigue') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R42', 'الدوخة والدوار', 'Dizziness and giddiness') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z00', 'فحص طبي عام', 'General medical examination') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z23', 'الحاجة للتطعيم', 'Need for immunization') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z71', 'استشارة طبية دون تشخيص', 'Persons seeking consultation without complaint or diagnosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A00', 'الكوليرا', 'Cholera') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A01', 'التيفوئيد والباراتيفوئيد', 'Typhoid and paratyphoid fevers') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A03', 'الشيغيلا (الزحار الجرثومي)', 'Shigellosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A08', 'عدوى معوية فيروسية', 'Viral intestinal infection') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A37', 'السعال الديكي', 'Whooping cough') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A41', 'تعفن الدم (Sepsis)', 'Sepsis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A46', 'الحمرة (Erysipelas)', 'Erysipelas') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A49', 'عدوى جرثومية غير محددة الموضع', 'Bacterial infection of unspecified site') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'A90', 'حمى الضنك', 'Dengue fever') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B01', 'جدري الماء (Varicella)', 'Varicella (Chickenpox)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B05', 'الحصبة', 'Measles') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B06', 'الحصبة الألمانية', 'Rubella') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B26', 'النكاف', 'Mumps') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B35', 'عدوى فطرية جلدية (Tinea)', 'Dermatophytosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B37', 'داء المبيضات (Candidiasis)', 'Candidiasis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'B86', 'الجرب (Scabies)', 'Scabies') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'D69', 'اضطرابات التخثر ونقص الصفائح', 'Purpura and other hemorrhagic conditions') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'D72', 'اضطرابات كريات الدم البيضاء', 'Disorders of white blood cells') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'D80', 'نقص المناعة مع نقص الأجسام المضادة', 'Immunodeficiency with predominant antibody defects') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E04', 'تضخم الغدة الدرقية غير السام', 'Nontoxic goiter') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E16', 'اضطرابات إفراز البنكرياس الداخلي الأخرى', 'Other disorders of pancreatic internal secretion') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E27', 'اضطرابات الغدة الكظرية الأخرى', 'Other disorders of adrenal gland') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E44', 'سوء التغذية بروتيني-طاقي متوسط', 'Protein-energy malnutrition, moderate') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E55', 'نقص فيتامين د', 'Vitamin D deficiency') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E56', 'نقص فيتامينات أخرى', 'Other vitamin deficiency') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E61', 'نقص عناصر التغذية الأخرى', 'Deficiency of other nutrient elements') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E83', 'اضطرابات استقلاب المعادن', 'Disorders of mineral metabolism') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'E87', 'اضطرابات توازن السوائل والكهارل', 'Other disorders of fluid, electrolyte balance') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F10', 'اضطرابات مرتبطة بالكحول', 'Disorders due to alcohol use') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F20', 'الفصام (Schizophrenia)', 'Schizophrenia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F31', 'الاضطراب ثنائي القطب', 'Bipolar affective disorder') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F80', 'اضطرابات النمو النفسي الخاصة بالكلام واللغة', 'Specific developmental disorders of speech and language') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'F90', 'اضطرابات فرط الحركة (ADHD)', 'Hyperkinetic disorders (ADHD)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G20', 'مرض باركنسون', 'Parkinson''s disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G30', 'مرض ألزهايمر', 'Alzheimer''s disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G35', 'التصلب المتعدد', 'Multiple sclerosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G54', 'اضطرابات الجذور والضفائر العصبية', 'Nerve root and plexus disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G56', 'اعتلالات الأعصاب الطرفية بالطرف العلوي (متلازمة النفق الرسغي)', 'Mononeuropathies of upper limb (Carpal tunnel syndrome)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'G62', 'اعتلال الأعصاب المتعدد', 'Polyneuropathy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H00', 'الشحاذ (Stye) والتهاب الجفن', 'Hordeolum and chalazion') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H16', 'التهاب القرنية', 'Keratitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H26', 'الساد الآخر', 'Other cataract') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H40', 'الزَرَق (المياه الزرقاء / الجلوكوما)', 'Glaucoma') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H53', 'اضطرابات الرؤية', 'Visual disturbances') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H61', 'انسداد شمع الأذن', 'Impacted cerumen (Earwax blockage)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H81', 'اضطرابات الوظيفة الدهليزية (الدوار)', 'Disorders of vestibular function (Vertigo)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H90', 'فقدان السمع التوصيلي والحسي العصبي', 'Conductive and sensorineural hearing loss') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'H93', 'طنين الأذن', 'Tinnitus') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I05', 'أمراض الصمام التاجي الروماتيزمية', 'Rheumatic mitral valve diseases') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I25', 'مرض القلب الإقفاري المزمن', 'Chronic ischemic heart disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I26', 'الانصمام الرئوي', 'Pulmonary embolism') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I44', 'حصار القلب الأذيني البطيني', 'Atrioventricular block') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I47', 'تسرع القلب الانتيابي', 'Paroxysmal tachycardia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I80', 'التهاب الوريد والتخثر الوريدي', 'Phlebitis and thrombophlebitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I84', 'البواسير', 'Hemorrhoids') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'I95', 'انخفاض ضغط الدم', 'Hypotension') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J11', 'الإنفلونزا', 'Influenza') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J30', 'التهاب الأنف التحسسي', 'Vasomotor and allergic rhinitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J32', 'التهاب الجيوب الأنفية المزمن', 'Chronic sinusitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J35', 'أمراض اللوزتين واللحمية المزمنة', 'Chronic diseases of tonsils and adenoids') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J40', 'التهاب الشعب الهوائية غير محدد', 'Bronchitis, not specified as acute or chronic') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J46', 'حالة ربو حادة', 'Status asthmaticus') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'J93', 'استرواح الصدر (Pneumothorax)', 'Pneumothorax') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K04', 'أمراض لب السن والأنسجة المحيطة', 'Diseases of pulp and periapical tissues') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K05', 'التهاب اللثة وأمراض اللثة', 'Gingivitis and periodontal diseases') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K12', 'التهاب الفم وآفات مرتبطة', 'Stomatitis and related lesions') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K40', 'الفتق الإربي', 'Inguinal hernia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K44', 'الفتق الحجابي', 'Diaphragmatic hernia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K52', 'التهاب المعدة والأمعاء غير المعدي', 'Noninfective gastroenteritis and colitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K57', 'داء الرتوج المعوي', 'Diverticular disease of intestine') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K62', 'أمراض الشرج والمستقيم الأخرى', 'Other diseases of anus and rectum') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K70', 'مرض الكبد الكحولي', 'Alcoholic liver disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K74', 'تليف وتشمع الكبد', 'Fibrosis and cirrhosis of liver') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K76', 'مرض الكبد الدهني', 'Fatty liver disease') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K81', 'التهاب المرارة', 'Cholecystitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'K85', 'التهاب البنكرياس الحاد', 'Acute pancreatitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L01', 'القوباء (Impetigo)', 'Impetigo') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L02', 'خراج جلدي ودمل', 'Cutaneous abscess, furuncle') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L03', 'التهاب النسيج الخلوي (Cellulitis)', 'Cellulitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L60', 'اضطرابات الأظافر', 'Nail disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L70', 'حب الشباب', 'Acne') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'L84', 'الكالو والمسمار (Corns and callosities)', 'Corns and callosities') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M16', 'خشونة مفصل الورك', 'Osteoarthritis of hip') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M17', 'خشونة مفصل الركبة', 'Osteoarthritis of knee') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M23', 'اضطرابات داخلية بمفصل الركبة (إصابة الغضروف الهلالي)', 'Internal derangement of knee (Meniscus)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M32', 'الذئبة الحمامية الجهازية', 'Systemic lupus erythematosus') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M47', 'داء الفقار المتعظم (Spondylosis)', 'Spondylosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M51', 'اضطرابات القرص الفقري الأخرى', 'Other intervertebral disc disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M53', 'اعتلالات ظهرية أخرى', 'Other dorsopathies') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M62', 'اضطرابات عضلية أخرى', 'Other disorders of muscle') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M75', 'آفات الكتف (تجمد الكتف)', 'Shoulder lesions (Frozen shoulder)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'M81', 'هشاشة العظام بدون كسر مرضي', 'Osteoporosis without pathological fracture') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N41', 'التهاب البروستاتا', 'Inflammatory diseases of prostate') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N43', 'قيلة مائية وقيلة منوية', 'Hydrocele and spermatocele') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N60', 'اعتلال الثدي الحميد', 'Benign mammary dysplasia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N70', 'التهاب البوق والمبيض', 'Salpingitis and oophoritis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N76', 'التهاب المهبل الحاد', 'Acute vaginitis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N80', 'الانتباذ البطاني الرحمي (Endometriosis)', 'Endometriosis') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N81', 'هبوط الأعضاء التناسلية الأنثوية', 'Female genital prolapse') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N92', 'اضطرابات الطمث الغزير وغير المنتظم', 'Excessive, frequent and irregular menstruation') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'N95', 'اضطرابات سن اليأس', 'Menopausal and other perimenopausal disorders') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O03', 'الإجهاض التلقائي', 'Spontaneous abortion') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O14', 'تسمم الحمل (Pre-eclampsia)', 'Pre-eclampsia') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O21', 'غثيان وقيء الحمل الشديد', 'Excessive vomiting in pregnancy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O23', 'عدوى الجهاز البولي بالحمل', 'Infections of genitourinary tract in pregnancy') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O24', 'سكري الحمل', 'Diabetes mellitus in pregnancy (Gestational)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O60', 'المخاض المبكر', 'Preterm labour') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'O82', 'الولادة القيصرية', 'Single delivery by caesarean section') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'P07', 'الخداج ونقص وزن الولادة', 'Disorders related to short gestation and low birth weight') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'P59', 'اليرقان الوليدي', 'Neonatal jaundice') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Q21', 'تشوهات خلقية بحاجز القلب', 'Congenital malformations of cardiac septa') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Q65', 'تشوهات خلقية بمفصل الورك', 'Congenital deformities of hip') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S00', 'إصابة سطحية بالرأس', 'Superficial injury of head') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S01', 'جرح مفتوح بالرأس', 'Open wound of head') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S42', 'كسر الكتف والعضد', 'Fracture of shoulder and upper arm') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S62', 'كسر بالرسغ ومستوى اليد', 'Fracture at wrist and hand level') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S72', 'كسر عظم الفخذ', 'Fracture of femur') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'S93', 'التواء وإجهاد بمستوى الكاحل والقدم', 'Sprain and strain of ankle and foot') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'T14', 'إصابة بمنطقة جسدية غير محددة', 'Injury of unspecified body region') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'T30', 'حروق بمنطقة جسدية غير محددة', 'Burn, unspecified body region') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'T78', 'التأثيرات الضارة، غير مصنفة بمكان آخر (تحسس حساسية مفرطة)', 'Adverse effects, not elsewhere classified (Anaphylaxis)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'W19', 'السقوط غير محدد', 'Unspecified fall') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'X58', 'التعرض لعامل غير محدد بالحادثة', 'Exposure to other specified factors') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R00', 'شذوذات ضربات القلب', 'Abnormalities of heart beat') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R06', 'شذوذات التنفس (ضيق التنفس)', 'Abnormalities of breathing') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R09', 'أعراض وعلامات أخرى بالجهاز التنفسي', 'Other symptoms of respiratory system') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R19', 'أعراض بالجهاز الهضمي والبطن الأخرى', 'Other symptoms of digestive system and abdomen') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R21', 'الطفح الجلدي', 'Rash and other nonspecific skin eruption') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R55', 'الإغماء والانهيار', 'Syncope and collapse') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R56', 'التشنجات', 'Convulsions') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R60', 'الوذمة (تورم)', 'Edema') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'R63', 'أعراض متعلقة بتناول الطعام والسوائل (فقدان الشهية)', 'Symptoms concerning food and fluid intake') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z01', 'فحوصات وتحاليل خاصة أخرى', 'Other special examinations and investigations') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z30', 'إدارة تنظيم النسل', 'Contraceptive management') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z32', 'فحص وتأكيد الحمل', 'Pregnancy examination and test') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z51', 'رعاية طبية أخرى (علاج كيماوي/إشعاعي)', 'Other medical care (Chemotherapy/Radiotherapy)') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en) VALUES ('icd', 'Z76', 'أشخاص يتصلون بالخدمات الصحية بظروف أخرى', 'Persons encountering health services in other circumstances') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '61462000', 'ورم خبيث بالدماغ', 'Malignant neoplasm of brain', NULL) ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '254837009', 'ورم خبيث بالثدي', 'Malignant neoplasm of breast', 'C50') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '399068003', 'ورم خبيث بالبروستاتا', 'Malignant tumor of prostate', 'C61') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '363358000', 'ورم خبيث بالرئة', 'Malignant tumor of lung', 'C34') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '87522002', 'فقر دم بعوز الحديد', 'Iron deficiency anemia', 'D50') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '271737000', 'فقر الدم', 'Anemia', 'D64') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '40930008', 'قصور الغدة الدرقية', 'Hypothyroidism', 'E03') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '34486009', 'فرط نشاط الغدة الدرقية', 'Hyperthyroidism', 'E05') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '46635009', 'داء السكري النوع الأول', 'Type 1 diabetes mellitus', 'E10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '44054006', 'داء السكري النوع الثاني', 'Type 2 diabetes mellitus', 'E11') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '414916001', 'السمنة', 'Obesity', 'E66') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '55822004', 'اضطراب استقلاب الدهون', 'Hyperlipidemia', 'E78') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '34095006', 'الجفاف', 'Dehydration', 'E86') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '35489007', 'نوبة اكتئابية', 'Depressive disorder', 'F32') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '48694002', 'اضطراب القلق', 'Anxiety disorder', 'F41') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '193462001', 'الأرق', 'Insomnia', 'F51') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '84757009', 'الصرع', 'Epilepsy', 'G40') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '37796009', 'الصداع النصفي', 'Migraine', 'G43') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '9826008', 'التهاب الملتحمة', 'Conjunctivitis', 'H10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '193570009', 'الساد الشيخوخي', 'Senile cataract', 'H25') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '278516003', 'اضطراب انكسار العين', 'Refractive error', 'H52') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '43275000', 'التهاب الأذن الخارجية', 'Otitis externa', 'H60') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '65363002', 'التهاب الأذن الوسطى', 'Otitis media', 'H66') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '38341003', 'ارتفاع ضغط الدم', 'Hypertensive disorder', 'I10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '194828000', 'الذبحة الصدرية', 'Angina pectoris', 'I20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '22298006', 'احتشاء عضلة القلب', 'Myocardial infarction', 'I21') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '49436004', 'الرجفان الأذيني', 'Atrial fibrillation', 'I48') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '84114007', 'قصور القلب', 'Heart failure', 'I50') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '230690007', 'السكتة الدماغية', 'Cerebrovascular accident (Stroke)', 'I63') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128064003', 'دوالي الأطراف السفلية', 'Varicose veins of lower extremity', 'I83') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '82272006', 'الزكام (نزلة برد)', 'Common cold', 'J00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '15805002', 'التهاب الجيوب الأنفية الحاد', 'Acute sinusitis', 'J01') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '363746003', 'التهاب البلعوم الحاد', 'Acute pharyngitis', 'J02') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '90176007', 'التهاب اللوزتين الحاد', 'Acute tonsillitis', 'J03') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '54150009', 'عدوى الجهاز التنفسي العلوي الحادة', 'Acute upper respiratory infection', 'J06') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '233604007', 'الالتهاب الرئوي', 'Pneumonia', 'J18') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '10509002', 'التهاب الشعب الهوائية الحاد', 'Acute bronchitis', 'J20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '13645005', 'مرض الانسداد الرئوي المزمن', 'Chronic obstructive pulmonary disease', 'J44') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '195967001', 'الربو', 'Asthma', 'J45') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '80967001', 'تسوس الأسنان', 'Dental caries', 'K02') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '235595009', 'ارتجاع المريء', 'Gastroesophageal reflux disease', 'K21') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '397825006', 'قرحة المعدة', 'Peptic ulcer', 'K25') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '4556007', 'التهاب المعدة والاثني عشر', 'Gastritis', 'K29') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '74400008', 'التهاب الزائدة الدودية الحاد', 'Acute appendicitis', 'K35') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '10743008', 'متلازمة القولون العصبي', 'Irritable bowel syndrome', 'K58') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '14760008', 'الإمساك', 'Constipation', 'K59') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '235919008', 'حصى المرارة', 'Cholelithiasis', 'K80') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '24079001', 'الأكزيما التأتبية', 'Atopic dermatitis', 'L20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '238539001', 'التهاب الجلد التماسي', 'Contact dermatitis', 'L23') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '9014002', 'الصدفية', 'Psoriasis', 'L40') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '126485001', 'الشرى (الأرتيكاريا)', 'Urticaria', 'L50') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '396275006', 'الفصال العظمي (خشونة المفاصل)', 'Osteoarthritis', 'M19') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '69896004', 'التهاب المفاصل الروماتويدي', 'Rheumatoid arthritis', 'M06') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '90560007', 'النقرس', 'Gout', 'M10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '279039007', 'ألم الظهر', 'Back pain', 'M54') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '36225005', 'التهاب الكلية والحويضة الحاد', 'Acute pyelonephritis', 'N10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '709044004', 'مرض الكلى المزمن', 'Chronic kidney disease', 'N18') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '95570007', 'حصى الكلى', 'Renal calculus', 'N20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '38822007', 'التهاب المثانة', 'Cystitis', 'N30') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '68566005', 'عدوى المسالك البولية', 'Urinary tract infection', 'N39') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '266569009', 'تضخم البروستاتا الحميد', 'Benign prostatic hyperplasia', 'N40') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '77386006', 'مراقبة حمل طبيعي', 'Pregnancy', 'Z34') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '281050002', 'ولادة طبيعية', 'Spontaneous delivery', 'O80') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '110030002', 'إصابة داخل القحف', 'Intracranial injury', 'S06') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '298178008', 'كسر الساعد', 'Fracture of forearm', 'S52') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '283533003', 'كسر أسفل الساق', 'Fracture of lower leg', 'S82') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '49727002', 'السعال', 'Cough', 'R05') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '29857009', 'ألم الصدر', 'Chest pain', 'R07') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '21522001', 'ألم البطن', 'Abdominal pain', 'R10') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '422587007', 'الغثيان', 'Nausea', 'R11') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '386661006', 'الحمى', 'Fever', 'R50') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '25064002', 'الصداع', 'Headache', 'R51') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '84229001', 'الإرهاق', 'Fatigue', 'R53') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '404640003', 'الدوخة', 'Dizziness', 'R42') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '162673000', 'فحص طبي عام', 'General examination of patient', 'Z00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '171207006', 'التطعيم', 'Immunization', 'Z23') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '63650001', 'الكوليرا', 'Cholera', 'A00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '4834000', 'التيفوئيد', 'Typhoid fever', 'A01') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '76902006', 'الشيغيلا', 'Shigellosis', 'A03') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '27836007', 'السعال الديكي', 'Pertussis (Whooping cough)', 'A37') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '91302008', 'تعفن الدم', 'Sepsis', 'A41') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '38362002', 'حمى الضنك', 'Dengue fever', 'A90') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '38907003', 'جدري الماء', 'Varicella', 'B01') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '14189004', 'الحصبة', 'Measles', 'B05') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '36653000', 'الحصبة الألمانية', 'Rubella', 'B06') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '36989005', 'النكاف', 'Mumps', 'B26') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '78940005', 'عدوى فطرية جلدية', 'Dermatophytosis', 'B35') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '80612006', 'داء المبيضات', 'Candidiasis', 'B37') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '9740006', 'الجرب', 'Scabies', 'B86') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '267064002', 'تضخم الغدة الدرقية', 'Goiter', 'E04') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '34457002', 'سوء التغذية', 'Malnutrition', 'E44') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '34970009', 'نقص فيتامين د', 'Vitamin D deficiency', 'E55') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '58214004', 'الفصام', 'Schizophrenia', 'F20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '13746004', 'الاضطراب ثنائي القطب', 'Bipolar disorder', 'F31') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '406506008', 'اضطراب فرط الحركة ونقص الانتباه', 'Attention deficit hyperactivity disorder', 'F90') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '49049000', 'مرض باركنسون', 'Parkinson''s disease', 'G20') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '26929004', 'مرض ألزهايمر', 'Alzheimer''s disease', 'G30') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '24700007', 'التصلب المتعدد', 'Multiple sclerosis', 'G35') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '57406009', 'متلازمة النفق الرسغي', 'Carpal tunnel syndrome', 'G56') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128613002', 'اعتلال الأعصاب المتعدد', 'Polyneuropathy', 'G62') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '18718003', 'الشحاذ', 'Hordeolum (Stye)', 'H00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128473001', 'التهاب القرنية', 'Keratitis', 'H16') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '23986001', 'الزَرَق (الجلوكوما)', 'Glaucoma', 'H40') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '162290004', 'انسداد شمع الأذن', 'Earwax impaction', 'H61') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '399231001', 'الدوار الدهليزي', 'Vertigo', 'H81') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '124231000', 'فقدان السمع', 'Hearing loss', 'H90') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '60862001', 'طنين الأذن', 'Tinnitus', 'H93') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '65710008', 'مرض القلب الإقفاري المزمن', 'Chronic ischemic heart disease', 'I25') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '59282003', 'الانصمام الرئوي', 'Pulmonary embolism', 'I26') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '54016000', 'حصار القلب الأذيني البطيني', 'Atrioventricular block', 'I44') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '67198005', 'تسرع القلب الانتيابي', 'Paroxysmal tachycardia', 'I47') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128053008', 'التهاب الوريد الخثاري', 'Thrombophlebitis', 'I80') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '70153002', 'البواسير', 'Hemorrhoids', 'I84') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '45007003', 'انخفاض ضغط الدم', 'Hypotension', 'I95') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '6142004', 'الإنفلونزا', 'Influenza', 'J11') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '61582004', 'التهاب الأنف التحسسي', 'Allergic rhinitis', 'J30') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '40055000', 'التهاب الجيوب الأنفية المزمن', 'Chronic sinusitis', 'J32') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '708038006', 'حالة ربو حادة', 'Status asthmaticus', 'J46') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '36118008', 'استرواح الصدر', 'Pneumothorax', 'J93') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '3723001', 'التهاب لب السن', 'Pulpitis', 'K04') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '75478009', 'التهاب اللثة', 'Gingivitis', 'K05') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '397772001', 'التهاب الفم', 'Stomatitis', 'K12') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '396232000', 'الفتق الإربي', 'Inguinal hernia', 'K40') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '48333001', 'الفتق الحجابي', 'Diaphragmatic hernia', 'K44') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '32403008', 'داء الرتوج المعوي', 'Diverticular disease', 'K57') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '197360006', 'مرض الكبد الكحولي', 'Alcoholic liver disease', 'K70') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '19943007', 'تليف الكبد', 'Cirrhosis of liver', 'K74') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '197315008', 'مرض الكبد الدهني', 'Fatty liver disease', 'K76') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '65275009', 'التهاب المرارة', 'Cholecystitis', 'K81') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '197456007', 'التهاب البنكرياس الحاد', 'Acute pancreatitis', 'K85') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '48277006', 'القوباء', 'Impetigo', 'L01') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128045006', 'خراج جلدي', 'Skin abscess', 'L02') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '128041000', 'التهاب النسيج الخلوي', 'Cellulitis', 'L03') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '11381005', 'حب الشباب', 'Acne', 'L70') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '201826000', 'خشونة مفصل الورك', 'Osteoarthritis of hip', 'M16') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '239873007', 'خشونة مفصل الركبة', 'Osteoarthritis of knee', 'M17') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '55464009', 'الذئبة الحمامية الجهازية', 'Systemic lupus erythematosus', 'M32') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '52911004', 'داء الفقار المتعظم', 'Spondylosis', 'M47') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '298382003', 'اضطراب القرص الفقري', 'Intervertebral disc disorder', 'M51') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '72704001', 'تجمد الكتف', 'Frozen shoulder', 'M75') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '64859006', 'هشاشة العظام', 'Osteoporosis', 'M81') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '2807004', 'التهاب البروستاتا', 'Prostatitis', 'N41') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '3634006', 'قيلة مائية', 'Hydrocele', 'N43') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '90767005', 'التهاب البوق والمبيض', 'Salpingo-oophoritis', 'N70') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '78619005', 'التهاب المهبل', 'Vaginitis', 'N76') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '129103003', 'الانتباذ البطاني الرحمي', 'Endometriosis', 'N80') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '198436008', 'هبوط الرحم', 'Uterine prolapse', 'N81') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '289185002', 'اضطرابات سن اليأس', 'Menopausal disorder', 'N95') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '17369002', 'الإجهاض التلقائي', 'Spontaneous abortion', 'O03') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '398254007', 'تسمم الحمل', 'Pre-eclampsia', 'O14') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '11687002', 'اليرقان الوليدي', 'Neonatal jaundice', 'P59') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '312608009', 'إصابة سطحية بالرأس', 'Superficial injury of head', 'S00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '263201007', 'كسر الكتف والعضد', 'Fracture of shoulder', 'S42') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '71620000', 'كسر عظم الفخذ', 'Fracture of femur', 'S72') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '44465007', 'التواء الكاحل', 'Sprain of ankle', 'S93') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '125666000', 'الحروق', 'Burn', 'T30') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '39579001', 'الحساسية المفرطة (Anaphylaxis)', 'Anaphylaxis', 'T78') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '161891005', 'خفقان القلب', 'Palpitations', 'R00') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '267036007', 'ضيق التنفس', 'Dyspnea', 'R06') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '271807003', 'الطفح الجلدي', 'Skin rash', 'R21') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '271594007', 'الإغماء', 'Syncope', 'R55') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '91175000', 'التشنجات', 'Seizure', 'R56') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '267038008', 'الوذمة', 'Edema', 'R60') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '79890006', 'فقدان الشهية', 'Anorexia', 'R63') ON CONFLICT (system, code) DO NOTHING;
INSERT INTO medical_codes (system, code, name_ar, name_en, icd_link) VALUES ('snomed', '5251000', 'فحص وتأكيد الحمل', 'Pregnancy test', 'Z32') ON CONFLICT (system, code) DO NOTHING;
